### ISSUE TITLE
No microsevices architecture diagram can be complete without some kind of stickman!

### ISSUE THREAD

**Issue by davidhopkins** [lucasepe/draft#4]
Requesting the additional of a new kind or alteration of the cli kind to have a more visual representation of a user of the service i.e. the classic stickman

```
  O
 /|\  
_/ \_
```

**Comment by lucasepe** [comment]
:-) love the ascii art! yes! totally agree, will be present in the next release.

**Comment by lucasepe** [comment]
Add `kind: usr` to draw a _"user"_ figure in v0.8.0
