### ISSUE TITLE
Installation steps

### ISSUE THREAD

**Issue by jhonrocha** [lucasepe/draft#6]
Hey! Can you list somewhere how to install it? I am not a Go user, so I don't know the ecosystem and package manager. 
I know there is a binary and packages for some distros on the release, but I didn't find how to do it manually from the source.

**Comment by lucasepe** [comment]
Hi!

To build the binaries by yourself, assuming that you have Go installed, here the steps:

Clone the repo:

```bash
git clone https://github.com/lucasepe/draft.git
```
Move to the 'cmd' directory:

```bash
cd draft/cmd
```

Generate the static assets
```bash
go generate ../...
```

Build the binary tool

```bash
go build -o draft
```

**Comment by jhonrocha** [comment]
Thank you very much!

**Comment by Rubix982** [comment]
Thanks, @lucasepe ! I personally hadn't yet set this up for myself, and I'm a very big newbie to `Go` itself.

I thought maybe I should add the installation steps from here into the main `README.md` - which didn't have an installation step. Can you check that out whenever you get the time? Thanks! :D

I referenced the PR above.
